 # 어떤 이미지를 사용할지
FROM node:alpine AS development

WORKDIR /usr/src/app

# package.json 복사하기
COPY package*.json ./

# pnpm-lock.yaml
COPY pnpm-lock.yaml ./

# pnpm 설치하기
RUN npm i -g pnpm 

# Dependency 설치하기
RUN pnpm i

COPY . .

CMD ["pnpm", "start:dev", "user"]

